### PR TITLE
Update simpleforce dependency

### PR DESCRIPTION
**Pull request by aserdean**
The latest commit in the simpleforce logs salesforce errors.

Bump the dependency since this will help us trace the issues.

Signed-off-by: Alin-Gabriel Serdean <alin.serdean@ovn.org>

Resolves: #35

### CODE REVIEW

**Comment by aserdean** [comment]
Added another commit to solve `gofmt` errors

**Comment by hemanthnakkina** [comment]
LGTM!

**Comment by hemanthnakkina** [comment]
Alin, 

Can you edit first comment with  Resolves: #35
I think Resolves keyword will automatically tag/link PR to the issue

**Comment by aserdean** [comment]
Changed, thanks for the feedback!

**Pull request merged**
